name: flutter_bluetooth_serial
version: 0.2.2

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4

flutter:
  plugin:
    androidPackage: io.github.edufolly.flutterbluetoothserial
    pluginClass: FlutterBluetoothSerialPlugin

environment:
  sdk: ">=2.0.0-a <3.0.0"
